[project]
name = "proyecto-ia-backend"
version = "0.1.0"
description = "Estructura inicial para el backend."
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
